version: '3.7'

services:
  app:
    container_name: 'launchpad'
    hostname: 'launchpad'
    restart: 'always'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:7172:80'
